### ISSUE TITLE
Har behov for litt mer info

### ISSUE THREAD

**Issue by tvs-brreg** [brreg/br-contrast#2]
Eg tror det hadde vært nyttig å hatt en forklaring eller vise til en plass som forklarer hva APCA og LC verdi er og hvorfor "minimum value" blir endret basert på input.

**Comment by Camulos** [comment]
Mulig tekst som kan legges til:
"APCA
[The Accessible Perceptual Contrast Algorithm](https://git.apcacontrast.com/documentation/WhyAPCA) (APCA) is a method for calculating and predicting readability contrast. APCA is a part of the larger S-Luv Accessible Color Appearance Model known as SACAM. These models are specifically related to color appearance on self-illuminated RGB computer displays & devices, and also for modeling accessible user needs, with a focus on readability."

"Lightness contrast (Lc)
APCA generates a lightness/darkness contrast value based on a minimum font size and color pair, and this value is perceptually based: that is, regardless of how light or dark the two colors are, a contrast value of Lc 60 represents the same perceived readability contrast."

**Comment by ohatland** [comment]
Har lagt inn teksten over som preview tekst i sidebaren som kommer opp for å vise fagesammentillingen
