### ISSUE TITLE
Failed contrast shown/hidden koblet til valgt kontrastkrav

### ISSUE THREAD

**Issue by Camulos** [brreg/br-contrast#4]
Velger en å skjule feilede farger, burde den bestemme hva som er feil ut fra hvilke krav som er valg i "Test for". 

Nå viser den alle farger som får suksess på minst en av de tre ser det ut som. Men den burde heller vise hvilke som får suksess på alle en har valgt og ignorere de som ikke er valgt? Dvs om en velger både APCA og WCAG 2 AAA så vises de som får "grønt" i begge settene, resultat av WCAG 2 AA blir da ignorert siden den ikke er valgt.

**Comment by ohatland** [comment]
fikset i [3b3cff1](https://github.com/brreg/br-contrast/commit/3b3cff18b14bd57ee6d7e8c0f68386d8ea44ea9b)
